apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZV3hsZUcxbGJuUmxaRHBuYUhCZlQycFpSbTh3T1hKMFFtTlhTV2d6WkZCMk1ETk9UV1UzWkZSYWN6RnhNVnBMTlRSVyIKCQl9Cgl9LAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0=
type: kubernetes.io/dockerconfigjson
